const terms = [
  {
    term: "VR (Viva Reseller)",
    definition:
      "Newly enrolled IndusViva direct seller who can only resell. They are eligible only for the retail revenue.",
  },
  {
    term: "VBO (Viva Business Owner)",
    definition:
      "A direct seller who can enroll new VRs, access genealogy and earn Dual Team Revenue and other revenues.",
  },
  {
    term: "DIRECT SELLER",
    definition:
      "VR or VBOs are combinedly known as direct sellers. It has the same meaning as mentioned in the Consumer Protection (Direct Selling) Rules 2021.",
  },
  {
    term: "CUSTOMER/CONSUMER",
    definition:
      "A person who is not a direct seller but purchases IndusViva products through their store link or directly from direct sellers. It has the same meaning as mentioned in Consumer Protection Act 2019.",
  },
  {
    term: "STORE LINK",
    definition:
      "The link generated from the Virtual Office of the direct seller by clicking which a customer can place order for his/her choice of products.",
  },
  {
    term: "UNIQUE CUSTOMER",
    definition:
      "A customer with unique mobile number, email id, address and bank account/UPI/card/any other payment mode which do not match with another customer.",
  },
  {
    term: "RETAIL",
    definition:
      "Order placed/purchase made by a customer using store link of a direct seller.",
  },
  {
    term: "DP",
    definition: "Direct Seller’s Price.",
  },
  {
    term: "MRP",
    definition: "Maximum Retail Price.",
  },
  {
    term: "PV (Point Value)",
    definition: "It’s the volume of the product sold by a direct seller.",
  },
  {
    term: "GV (Group Volume)",
    definition:
      "It’s the collective volume generated by a network/organisation (revenues and bonuses are calculated based on the turnover of GV & PV).",
  },
  {
    term: "GBU (Global Bonus Unit)",
    definition: "Gross revenue is represented in GBU.",
  },
  {
    term: "GROSS REVENUE",
    definition:
      "The sum of all types of revenues and bonuses (bonuses that are paid as money) earned in a week.",
  },
  {
    term: "AGGREGATED REVENUE",
    definition:
      "The sum of gross revenue earned from the 1st order week to the last paid week.",
  },
  {
    term: "FIRST ORDER WEEK",
    definition: "The week in which the first retailing is done.",
  },
  {
    term: "FIRST ORDER",
    definition: "Aggregate retail volume in 1st order week of a VR.",
  },
  {
    term: "ACTIVE",
    definition:
      "Status of ID to be eligible for revenues, bonuses and other benefits. IDs get active through personal turnover generated through retail for 4 weeks or upgrading to presidential club.",
  },
  {
    term: "ACTIVATION LEVEL",
    definition:
      "The volume of PV generated in a direct seller’s ID through personal turnover within a cycle.",
  },
  {
    term: "PERSONAL TURNOVER",
    definition:
      "Business volume generated through personal retailing by a direct seller and the first order of personally sponsored VR of a VBO.",
  },
  {
    term: "ACTIVATED ID",
    definition: "An ID in which at least one retail order is placed.",
  },
  {
    term: "SPONSOR",
    definition: "A VBO who personally enrolls a VR to his/her organisation.",
  },
  {
    term: "SENIOR ASSOCIATE",
    definition: "A VBO who is placed ahead in a genealogical hierarchy.",
  },
  {
    term: "ASSOCIATE",
    definition: "A VBO who comes in referred VBO’s organisation/genealogy.",
  },
  {
    term: "CROSSLINE",
    definition:
      "A VBO who is from an entirely different organisation than of the referred VBO’s.",
  },
  {
    term: "MONTH",
    definition: "A calendar month.",
  },
  {
    term: "CYCLE",
    definition: "Period of any consecutive 4 weeks.",
  },
  {
    term: "WEEK OF CONTRACT",
    definition:
      "The week in which a VR agreed to the contract and got enrolled. Wherever, 1+1 or 1+2 week or similar usage for eligibility of any bonus/reward is mentioned, 1 is referred to the week of contract.",
  },
  {
    term: "COMPLIMENTARY PRODUCTS",
    definition:
      "Products given to a VBO as a bonus, which shall not carry any PV, on fulfilling certain eligibility criteria. Selling price is discounted and shipment charges paid by VBO within 3 cycles. iCharge is the only complimentary product.",
  },
  {
    term: "SALES ORDER HOLD",
    definition:
      "Restricting activities or denying access temporarily, usually during an internal investigation or legal dispute.",
  },
  {
    term: "PAID AS RANK",
    definition: "Current week’s performance level.",
  },
  {
    term: "SUSPENDED",
    definition:
      "Restricting access to the ID due to inactivity of over 6 months (26 weeks) as it is considered as resigned.",
  },
  {
    term: "VACATED",
    definition: "Released the KYDS documents.",
  },
  {
    term: "EXPIRED",
    definition:
      "Permanently removing the ID due to inactivity of 2 years from the last order or completion of 4 weeks from the week of contract without placing 1st order.",
  },
  {
    term: "TERMINATED",
    definition:
      "ID blacklisted and permanently restricting access due to breach of contract.",
  },
  {
    term: "RESIGNED",
    definition:
      "ID resigned by the direct seller for which the KYDS shall be released on completion of 13 weeks from the week of resignation.",
  },
  {
    term: "BERTH ID",
    definition:
      "The new organisations generated parallel to 1st & 2nd organisations on achieving the Black Diamond Ambassador rank.",
  },
  {
    term: "PT (Placement Tree)",
    definition:
      "The genealogy of a direct seller starting from his/her immediate associates placed at the immediate next level. This will be called organisation 1, 2, 3 and so on.",
  },
  {
    term: "PET (Personal Enrollment Tree)",
    definition:
      "It is a genealogy starting from the directly sponsored associates of a VBO and grows through their respective sponsored direct sellers and so on.",
  },
];

const Terminologies = () => (
  <div className="my-8">
    <h2 className="text-2xl font-semibold mb-4">Terminologies</h2>
    <ul className="list-disc pl-6 space-y-2">
      {terms.map(({ term, definition }, idx) => (
        <li key={idx}>
          <strong>{term}:</strong> {definition}
        </li>
      ))}
    </ul>
  </div>
);

export default Terminologies;
